### ISSUE TITLE
Authentication & Authorization

### ISSUE THREAD

**Issue by maemresen** [softengteam/survey-web#6]
Configure roles and users to authentication and authorization with AD.

**Comment by maemresen** [comment]
I think [this link](https://medium.com/@nydiarra/secure-a-spring-boot-rest-api-with-json-web-token-reference-to-angular-integration-e57a25806c50) will be useful for us. You were talking about JSON Web-Token. I have not seen any problem with changing web project from MVC to REST API. 

What do you think? @canmertc . Is the link given above is feasible for React?

**Comment by canmertc** [comment]
I have taken a look at the link provided by you. JWT fits our needs in terms of authentication and authorization.
But Spring Boot JWT integration which mentioned in the link might make the usage of Active Directory unnecessary.  The professor's advice can be taken on this subject. Or do you think Active Directory still has a plausible area of usage? @maemresen @canberkardic

**Comment by maemresen** [comment]
I did make a little search about it and I think [this link](https://stackoverflow.com/questions/30494383/using-jwt-with-active-directory-authentication-in-nodejs-backend) does explain our problem well.

Question: **Using JWT with Active Directory authentication in NodeJS backend**

And the best answer based on these two aspects : 

1) Is it reasonable to combine AD authorization with JWT as bearer token or what is the preferred way to build a secure backend + frontend utilizing AD for authentication?

2)  If JWT is a good idea, what is the best practice for securing endpoints using JWT? Is using a server side session reasonable?

According to my little search, if we use a system like AD, then we should not consider authentication stuff on front-end side. 

@canmertc @canberkardic

**Comment by maemresen** [comment]
completed at Spring.
